/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Cascade;
import frameweb.Collection;
import frameweb.DomainClass;
import frameweb.Fetch;
import frameweb.Order;

/**
 * A sample validator interface for {@link frameweb.DomainAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainAssociationValidator {
	boolean validate();

	boolean validateCollection(Collection value);
	boolean validateOrder(Order value);
	boolean validateCascade(Cascade value);
	boolean validateFetch(Fetch value);
	boolean validateSourceClass(DomainClass value);
	boolean validateTargetClass(DomainClass value);
}
