/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.ServiceAttribute;
import frameweb.ServiceOperation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.ServiceInterface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceInterfaceValidator {
	boolean validate();

	boolean validateServiceInterfaceOperation(EList<ServiceOperation> value);
	boolean validateServiceInterfaceAttribute(EList<ServiceAttribute> value);
}
