/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Binary;
import frameweb.Component;
import frameweb.Form;
import frameweb.Page;
import frameweb.Template;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.ViewPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewPackageValidator {
	boolean validate();

	boolean validateViewPackagePage(EList<Page> value);
	boolean validateViewPakageTemplate(EList<Template> value);
	boolean validateViewPackageForm(EList<Form> value);
	boolean validateViewPackageBinaryData(Binary value);
	boolean validateViewPackageComponent(EList<Component> value);
}
