/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.DAOAttribute;
import frameweb.DAOBaseOperation;
import frameweb.DAOInterfaceName;
import frameweb.DAOOperation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.DAOInterface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DAOInterfaceValidator {
	boolean validate();

	boolean validateOwnBaseOperation(EList<DAOBaseOperation> value);
	boolean validateOwnOperation(EList<DAOOperation> value);
	boolean validateDAOInterfaceName(DAOInterfaceName value);
	boolean validateDAOInterfaceAttribute(EList<DAOAttribute> value);
}
