/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.DomainColumnName;

/**
 * A sample validator interface for {@link frameweb.DomainAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainAttributeValidator {
	boolean validate();

	boolean validateSize(long value);
	boolean validateIsNull(boolean value);
	boolean validateIsPersistent(boolean value);
	boolean validateColumn(DomainColumnName value);
}
