/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Anotation;
import frameweb.Rule;
import frameweb.TagLib;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.Framework}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FrameworkValidator {
	boolean validate();

	boolean validateFrameworkTagLib(TagLib value);
	boolean validateFrameworkRule(EList<Rule> value);
	boolean validateFrameworkAnotation(EList<Anotation> value);
}
