/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Component;
import frameweb.JQuery;
import frameweb.Page;
import frameweb.Tag; //*********************************************** linha adicionada
import frameweb.Template;

/**
 * A sample validator interface for {@link frameweb.NavigationComposition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NavigationCompositionValidator {
	boolean validate();

	boolean validateSourceTemplate(Template value);
	boolean validateSourcePage(Page value);
	boolean validateTargetForm(Tag value);
	boolean validateTargetComponent(Component value);
	boolean validateTargetJQuery(JQuery value);
}
