/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Binary;
import frameweb.Component;
import frameweb.Form;
import frameweb.FormComponent;
import frameweb.FrontControllerClass;
import frameweb.FrontControllerMethod;
import frameweb.JQuery;
import frameweb.Page;
import frameweb.Result;
import frameweb.ResultType;
import frameweb.Template;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.ResultDependency}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResultDependencyValidator {
	boolean validate();

	boolean validateReturnResult(EList<Result> value);
	boolean validateReturnMethod(FrontControllerMethod value);
	boolean validateSourceFrontController(FrontControllerClass value);
	boolean validateTargetTemplate(Template value);
	boolean validateTargetPage(Page value);
	boolean validateTargetBinary(Binary value);
	boolean validateReturnResultType(EList<ResultType> value);
	boolean validateTargetForm(Form value);
	boolean validateTargetComponent(Component value);
	boolean validateTargetJQuery(JQuery value);
	boolean validateTargetFormComponent(FormComponent value);
}
