/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.ServiceClass;
import frameweb.ServiceInterface;

/**
 * A sample validator interface for {@link frameweb.ServiceGeneralization}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceGeneralizationValidator {
	boolean validate();

	boolean validateSourceServiceInterface(ServiceInterface value);
	boolean validateTargetServiceClass(ServiceClass value);
}
