/**
 */
package frameweb.provider;

import frameweb.util.FramewebAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FramewebItemProviderAdapterFactory extends FramewebAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FramewebItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.FramewebProject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FramewebProjectItemProvider framewebProjectItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.FramewebProject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFramewebProjectAdapter() {
		if (framewebProjectItemProvider == null) {
			framewebProjectItemProvider = new FramewebProjectItemProvider(this);
		}

		return framewebProjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.FrameworkProfile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrameworkProfileItemProvider frameworkProfileItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.FrameworkProfile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrameworkProfileAdapter() {
		if (frameworkProfileItemProvider == null) {
			frameworkProfileItemProvider = new FrameworkProfileItemProvider(this);
		}

		return frameworkProfileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityModelItemProvider entityModelItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityModelAdapter() {
		if (entityModelItemProvider == null) {
			entityModelItemProvider = new EntityModelItemProvider(this);
		}

		return entityModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NavigationModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationModelItemProvider navigationModelItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NavigationModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationModelAdapter() {
		if (navigationModelItemProvider == null) {
			navigationModelItemProvider = new NavigationModelItemProvider(this);
		}

		return navigationModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ApplicationModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationModelItemProvider applicationModelItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ApplicationModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationModelAdapter() {
		if (applicationModelItemProvider == null) {
			applicationModelItemProvider = new ApplicationModelItemProvider(this);
		}

		return applicationModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.PersistenceModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersistenceModelItemProvider persistenceModelItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.PersistenceModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersistenceModelAdapter() {
		if (persistenceModelItemProvider == null) {
			persistenceModelItemProvider = new PersistenceModelItemProvider(this);
		}

		return persistenceModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityAssociationItemProvider entityAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAssociationAdapter() {
		if (entityAssociationItemProvider == null) {
			entityAssociationItemProvider = new EntityAssociationItemProvider(this);
		}

		return entityAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VersionAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VersionAttributeItemProvider versionAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VersionAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVersionAttributeAdapter() {
		if (versionAttributeItemProvider == null) {
			versionAttributeItemProvider = new VersionAttributeItemProvider(this);
		}

		return versionAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.IdAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdAttributeItemProvider idAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.IdAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdAttributeAdapter() {
		if (idAttributeItemProvider == null) {
			idAttributeItemProvider = new IdAttributeItemProvider(this);
		}

		return idAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.LOBAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LOBAttributeItemProvider lobAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.LOBAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLOBAttributeAdapter() {
		if (lobAttributeItemProvider == null) {
			lobAttributeItemProvider = new LOBAttributeItemProvider(this);
		}

		return lobAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EmbeddedAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmbeddedAttributeItemProvider embeddedAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EmbeddedAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmbeddedAttributeAdapter() {
		if (embeddedAttributeItemProvider == null) {
			embeddedAttributeItemProvider = new EmbeddedAttributeItemProvider(this);
		}

		return embeddedAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DecimalAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecimalAttributeItemProvider decimalAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DecimalAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDecimalAttributeAdapter() {
		if (decimalAttributeItemProvider == null) {
			decimalAttributeItemProvider = new DecimalAttributeItemProvider(this);
		}

		return decimalAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DateTimeAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateTimeAttributeItemProvider dateTimeAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DateTimeAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateTimeAttributeAdapter() {
		if (dateTimeAttributeItemProvider == null) {
			dateTimeAttributeItemProvider = new DateTimeAttributeItemProvider(this);
		}

		return dateTimeAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Page} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageItemProvider pageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Page}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageAdapter() {
		if (pageItemProvider == null) {
			pageItemProvider = new PageItemProvider(this);
		}

		return pageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Template} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TemplateItemProvider templateItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Template}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTemplateAdapter() {
		if (templateItemProvider == null) {
			templateItemProvider = new TemplateItemProvider(this);
		}

		return templateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOInterfaceItemProvider daoInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOInterfaceAdapter() {
		if (daoInterfaceItemProvider == null) {
			daoInterfaceItemProvider = new DAOInterfaceItemProvider(this);
		}

		return daoInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOClassItemProvider daoClassItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOClassAdapter() {
		if (daoClassItemProvider == null) {
			daoClassItemProvider = new DAOClassItemProvider(this);
		}

		return daoClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAORealization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAORealizationItemProvider daoRealizationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAORealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAORealizationAdapter() {
		if (daoRealizationItemProvider == null) {
			daoRealizationItemProvider = new DAORealizationItemProvider(this);
		}

		return daoRealizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.FrontControllerClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerClassItemProvider frontControllerClassItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.FrontControllerClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerClassAdapter() {
		if (frontControllerClassItemProvider == null) {
			frontControllerClassItemProvider = new FrontControllerClassItemProvider(this);
		}

		return frontControllerClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.IOParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IOParameterItemProvider ioParameterItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.IOParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIOParameterAdapter() {
		if (ioParameterItemProvider == null) {
			ioParameterItemProvider = new IOParameterItemProvider(this);
		}

		return ioParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultDependencyItemProvider resultDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultDependencyAdapter() {
		if (resultDependencyItemProvider == null) {
			resultDependencyItemProvider = new ResultDependencyItemProvider(this);
		}

		return resultDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NavigationAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationAssociationItemProvider navigationAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NavigationAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationAssociationAdapter() {
		if (navigationAssociationItemProvider == null) {
			navigationAssociationItemProvider = new NavigationAssociationItemProvider(this);
		}

		return navigationAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.FrontControllerMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerMethodItemProvider frontControllerMethodItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.FrontControllerMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerMethodAdapter() {
		if (frontControllerMethodItemProvider == null) {
			frontControllerMethodItemProvider = new FrontControllerMethodItemProvider(this);
		}

		return frontControllerMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceClassItemProvider serviceClassItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceClassAdapter() {
		if (serviceClassItemProvider == null) {
			serviceClassItemProvider = new ServiceClassItemProvider(this);
		}

		return serviceClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceInterfaceItemProvider serviceInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceInterfaceAdapter() {
		if (serviceInterfaceItemProvider == null) {
			serviceInterfaceItemProvider = new ServiceInterfaceItemProvider(this);
		}

		return serviceInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceGeneralizationItemProvider serviceGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceGeneralizationAdapter() {
		if (serviceGeneralizationItemProvider == null) {
			serviceGeneralizationItemProvider = new ServiceGeneralizationItemProvider(this);
		}

		return serviceGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceControllerAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceControllerAssociationItemProvider serviceControllerAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceControllerAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceControllerAssociationAdapter() {
		if (serviceControllerAssociationItemProvider == null) {
			serviceControllerAssociationItemProvider = new ServiceControllerAssociationItemProvider(this);
		}

		return serviceControllerAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityClassItemProvider entityClassItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityClassAdapter() {
		if (entityClassItemProvider == null) {
			entityClassItemProvider = new EntityClassItemProvider(this);
		}

		return entityClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Result} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultItemProvider resultItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Result}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultAdapter() {
		if (resultItemProvider == null) {
			resultItemProvider = new ResultItemProvider(this);
		}

		return resultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.FrontControllerDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontControllerDependencyItemProvider frontControllerDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.FrontControllerDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontControllerDependencyAdapter() {
		if (frontControllerDependencyItemProvider == null) {
			frontControllerDependencyItemProvider = new FrontControllerDependencyItemProvider(this);
		}

		return frontControllerDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.PageDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageDependencyItemProvider pageDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.PageDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageDependencyAdapter() {
		if (pageDependencyItemProvider == null) {
			pageDependencyItemProvider = new PageDependencyItemProvider(this);
		}

		return pageDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ChainingDependency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChainingDependencyItemProvider chainingDependencyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ChainingDependency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChainingDependencyAdapter() {
		if (chainingDependencyItemProvider == null) {
			chainingDependencyItemProvider = new ChainingDependencyItemProvider(this);
		}

		return chainingDependencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOServiceAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOServiceAssociationItemProvider daoServiceAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOServiceAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOServiceAssociationAdapter() {
		if (daoServiceAssociationItemProvider == null) {
			daoServiceAssociationItemProvider = new DAOServiceAssociationItemProvider(this);
		}

		return daoServiceAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityMethodItemProvider entityMethodItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityMethodAdapter() {
		if (entityMethodItemProvider == null) {
			entityMethodItemProvider = new EntityMethodItemProvider(this);
		}

		return entityMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOAttributeItemProvider daoAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOAttributeAdapter() {
		if (daoAttributeItemProvider == null) {
			daoAttributeItemProvider = new DAOAttributeItemProvider(this);
		}

		return daoAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceMethodItemProvider serviceMethodItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceMethodAdapter() {
		if (serviceMethodItemProvider == null) {
			serviceMethodItemProvider = new ServiceMethodItemProvider(this);
		}

		return serviceMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceAttributeItemProvider serviceAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAttributeAdapter() {
		if (serviceAttributeItemProvider == null) {
			serviceAttributeItemProvider = new ServiceAttributeItemProvider(this);
		}

		return serviceAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOMethodItemProvider daoMethodItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOMethodAdapter() {
		if (daoMethodItemProvider == null) {
			daoMethodItemProvider = new DAOMethodItemProvider(this);
		}

		return daoMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityPackageItemProvider entityPackageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityPackageAdapter() {
		if (entityPackageItemProvider == null) {
			entityPackageItemProvider = new EntityPackageItemProvider(this);
		}

		return entityPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ViewPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewPackageItemProvider viewPackageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ViewPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewPackageAdapter() {
		if (viewPackageItemProvider == null) {
			viewPackageItemProvider = new ViewPackageItemProvider(this);
		}

		return viewPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ControllerPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerPackageItemProvider controllerPackageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ControllerPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerPackageAdapter() {
		if (controllerPackageItemProvider == null) {
			controllerPackageItemProvider = new ControllerPackageItemProvider(this);
		}

		return controllerPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.PersistencePackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersistencePackageItemProvider persistencePackageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.PersistencePackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersistencePackageAdapter() {
		if (persistencePackageItemProvider == null) {
			persistencePackageItemProvider = new PersistencePackageItemProvider(this);
		}

		return persistencePackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ApplicationPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationPackageItemProvider applicationPackageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ApplicationPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationPackageAdapter() {
		if (applicationPackageItemProvider == null) {
			applicationPackageItemProvider = new ApplicationPackageItemProvider(this);
		}

		return applicationPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.UIComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIComponentItemProvider uiComponentItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.UIComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIComponentAdapter() {
		if (uiComponentItemProvider == null) {
			uiComponentItemProvider = new UIComponentItemProvider(this);
		}

		return uiComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultTypeItemProvider resultTypeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultTypeAdapter() {
		if (resultTypeItemProvider == null) {
			resultTypeItemProvider = new ResultTypeItemProvider(this);
		}

		return resultTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityGeneralizationItemProvider entityGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityGeneralizationAdapter() {
		if (entityGeneralizationItemProvider == null) {
			entityGeneralizationItemProvider = new EntityGeneralizationItemProvider(this);
		}

		return entityGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UIComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIComponentFieldItemProvider uiComponentFieldItemProvider;

	/**
	 * This creates an adapter for a {@link UIComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIComponentFieldAdapter() {
		if (uiComponentFieldItemProvider == null) {
			uiComponentFieldItemProvider = new UIComponentFieldItemProvider(this);
		}

		return uiComponentFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.TagLib} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagLibItemProvider tagLibItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.TagLib}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagLibAdapter() {
		if (tagLibItemProvider == null) {
			tagLibItemProvider = new TagLibItemProvider(this);
		}

		return tagLibItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Tag} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagItemProvider tagItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Tag}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagAdapter() {
		if (tagItemProvider == null) {
			tagItemProvider = new TagItemProvider(this);
		}

		return tagItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NavigationCompositionPart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationCompositionPartItemProvider navigationCompositionPartItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NavigationCompositionPart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationCompositionPartAdapter() {
		if (navigationCompositionPartItemProvider == null) {
			navigationCompositionPartItemProvider = new NavigationCompositionPartItemProvider(this);
		}

		return navigationCompositionPartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NavigationCompositionWhole} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationCompositionWholeItemProvider navigationCompositionWholeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NavigationCompositionWhole}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationCompositionWholeAdapter() {
		if (navigationCompositionWholeItemProvider == null) {
			navigationCompositionWholeItemProvider = new NavigationCompositionWholeItemProvider(this);
		}

		return navigationCompositionWholeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultSetItemProvider resultSetItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultSetAdapter() {
		if (resultSetItemProvider == null) {
			resultSetItemProvider = new ResultSetItemProvider(this);
		}

		return resultSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.PageConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageConstraintItemProvider pageConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.PageConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageConstraintAdapter() {
		if (pageConstraintItemProvider == null) {
			pageConstraintItemProvider = new PageConstraintItemProvider(this);
		}

		return pageConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultConstraintItemProvider resultConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultConstraintAdapter() {
		if (resultConstraintItemProvider == null) {
			resultConstraintItemProvider = new ResultConstraintItemProvider(this);
		}

		return resultConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.MethodCosntraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodCosntraintItemProvider methodCosntraintItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.MethodCosntraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodCosntraintAdapter() {
		if (methodCosntraintItemProvider == null) {
			methodCosntraintItemProvider = new MethodCosntraintItemProvider(this);
		}

		return methodCosntraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ChainingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChainingConstraintItemProvider chainingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ChainingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChainingConstraintAdapter() {
		if (chainingConstraintItemProvider == null) {
			chainingConstraintItemProvider = new ChainingConstraintItemProvider(this);
		}

		return chainingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NavigationGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationGeneralizationItemProvider navigationGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NavigationGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationGeneralizationAdapter() {
		if (navigationGeneralizationItemProvider == null) {
			navigationGeneralizationItemProvider = new NavigationGeneralizationItemProvider(this);
		}

		return navigationGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityConstraints} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityConstraintsItemProvider entityConstraintsItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityConstraints}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityConstraintsAdapter() {
		if (entityConstraintsItemProvider == null) {
			entityConstraintsItemProvider = new EntityConstraintsItemProvider(this);
		}

		return entityConstraintsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityPropertyItemProvider entityPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityPropertyAdapter() {
		if (entityPropertyItemProvider == null) {
			entityPropertyItemProvider = new EntityPropertyItemProvider(this);
		}

		return entityPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOGeneralization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOGeneralizationItemProvider daoGeneralizationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOGeneralization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOGeneralizationAdapter() {
		if (daoGeneralizationItemProvider == null) {
			daoGeneralizationItemProvider = new DAOGeneralizationItemProvider(this);
		}

		return daoGeneralizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.MappingLib} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappingLibItemProvider mappingLibItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.MappingLib}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappingLibAdapter() {
		if (mappingLibItemProvider == null) {
			mappingLibItemProvider = new MappingLibItemProvider(this);
		}

		return mappingLibItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ClassMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMappingItemProvider classMappingItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ClassMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMappingAdapter() {
		if (classMappingItemProvider == null) {
			classMappingItemProvider = new ClassMappingItemProvider(this);
		}

		return classMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.AttributeMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingItemProvider attributeMappingItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.AttributeMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingAdapter() {
		if (attributeMappingItemProvider == null) {
			attributeMappingItemProvider = new AttributeMappingItemProvider(this);
		}

		return attributeMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.EntityGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityGeneralizationSetItemProvider entityGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.EntityGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityGeneralizationSetAdapter() {
		if (entityGeneralizationSetItemProvider == null) {
			entityGeneralizationSetItemProvider = new EntityGeneralizationSetItemProvider(this);
		}

		return entityGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.TagExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagExtensionItemProvider tagExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.TagExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagExtensionAdapter() {
		if (tagExtensionItemProvider == null) {
			tagExtensionItemProvider = new TagExtensionItemProvider(this);
		}

		return tagExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.FrameworkApplication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrameworkApplicationItemProvider frameworkApplicationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.FrameworkApplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrameworkApplicationAdapter() {
		if (frameworkApplicationItemProvider == null) {
			frameworkApplicationItemProvider = new FrameworkApplicationItemProvider(this);
		}

		return frameworkApplicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ControllerExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerExtensionItemProvider controllerExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ControllerExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerExtensionAdapter() {
		if (controllerExtensionItemProvider == null) {
			controllerExtensionItemProvider = new ControllerExtensionItemProvider(this);
		}

		return controllerExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Controller} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerItemProvider controllerItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Controller}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerAdapter() {
		if (controllerItemProvider == null) {
			controllerItemProvider = new ControllerItemProvider(this);
		}

		return controllerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ControllerSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerSetItemProvider controllerSetItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ControllerSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerSetAdapter() {
		if (controllerSetItemProvider == null) {
			controllerSetItemProvider = new ControllerSetItemProvider(this);
		}

		return controllerSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultExtensionItemProvider resultExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultExtensionAdapter() {
		if (resultExtensionItemProvider == null) {
			resultExtensionItemProvider = new ResultExtensionItemProvider(this);
		}

		return resultExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ClassMappingExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMappingExtensionItemProvider classMappingExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ClassMappingExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMappingExtensionAdapter() {
		if (classMappingExtensionItemProvider == null) {
			classMappingExtensionItemProvider = new ClassMappingExtensionItemProvider(this);
		}

		return classMappingExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.AttributeMappingExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingExtensionItemProvider attributeMappingExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.AttributeMappingExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingExtensionAdapter() {
		if (attributeMappingExtensionItemProvider == null) {
			attributeMappingExtensionItemProvider = new AttributeMappingExtensionItemProvider(this);
		}

		return attributeMappingExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ControllerExtensionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerExtensionEndItemProvider controllerExtensionEndItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ControllerExtensionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerExtensionEndAdapter() {
		if (controllerExtensionEndItemProvider == null) {
			controllerExtensionEndItemProvider = new ControllerExtensionEndItemProvider(this);
		}

		return controllerExtensionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.TagExtensionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagExtensionEndItemProvider tagExtensionEndItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.TagExtensionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagExtensionEndAdapter() {
		if (tagExtensionEndItemProvider == null) {
			tagExtensionEndItemProvider = new TagExtensionEndItemProvider(this);
		}

		return tagExtensionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultExtensionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultExtensionEndItemProvider resultExtensionEndItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultExtensionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultExtensionEndAdapter() {
		if (resultExtensionEndItemProvider == null) {
			resultExtensionEndItemProvider = new ResultExtensionEndItemProvider(this);
		}

		return resultExtensionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ClassMappingExtensionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMappingExtensionEndItemProvider classMappingExtensionEndItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ClassMappingExtensionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMappingExtensionEndAdapter() {
		if (classMappingExtensionEndItemProvider == null) {
			classMappingExtensionEndItemProvider = new ClassMappingExtensionEndItemProvider(this);
		}

		return classMappingExtensionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.AttributeMappingExtensionEnd} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingExtensionEndItemProvider attributeMappingExtensionEndItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.AttributeMappingExtensionEnd}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingExtensionEndAdapter() {
		if (attributeMappingExtensionEndItemProvider == null) {
			attributeMappingExtensionEndItemProvider = new AttributeMappingExtensionEndItemProvider(this);
		}

		return attributeMappingExtensionEndItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ControllerProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerPropertyItemProvider controllerPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ControllerProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerPropertyAdapter() {
		if (controllerPropertyItemProvider == null) {
			controllerPropertyItemProvider = new ControllerPropertyItemProvider(this);
		}

		return controllerPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.TagProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TagPropertyItemProvider tagPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.TagProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTagPropertyAdapter() {
		if (tagPropertyItemProvider == null) {
			tagPropertyItemProvider = new TagPropertyItemProvider(this);
		}

		return tagPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ResultProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResultPropertyItemProvider resultPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ResultProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResultPropertyAdapter() {
		if (resultPropertyItemProvider == null) {
			resultPropertyItemProvider = new ResultPropertyItemProvider(this);
		}

		return resultPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ClassMappingPropery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassMappingProperyItemProvider classMappingProperyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ClassMappingPropery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassMappingProperyAdapter() {
		if (classMappingProperyItemProvider == null) {
			classMappingProperyItemProvider = new ClassMappingProperyItemProvider(this);
		}

		return classMappingProperyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.AttributeMappingProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeMappingPropertyItemProvider attributeMappingPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.AttributeMappingProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeMappingPropertyAdapter() {
		if (attributeMappingPropertyItemProvider == null) {
			attributeMappingPropertyItemProvider = new AttributeMappingPropertyItemProvider(this);
		}

		return attributeMappingPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.SeviceRealization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeviceRealizationItemProvider seviceRealizationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.SeviceRealization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSeviceRealizationAdapter() {
		if (seviceRealizationItemProvider == null) {
			seviceRealizationItemProvider = new SeviceRealizationItemProvider(this);
		}

		return seviceRealizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NavigationGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationGeneralizationSetItemProvider navigationGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NavigationGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationGeneralizationSetAdapter() {
		if (navigationGeneralizationSetItemProvider == null) {
			navigationGeneralizationSetItemProvider = new NavigationGeneralizationSetItemProvider(this);
		}

		return navigationGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DAOGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DAOGeneralizationSetItemProvider daoGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DAOGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDAOGeneralizationSetAdapter() {
		if (daoGeneralizationSetItemProvider == null) {
			daoGeneralizationSetItemProvider = new DAOGeneralizationSetItemProvider(this);
		}

		return daoGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ServiceGeneralizationSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceGeneralizationSetItemProvider serviceGeneralizationSetItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ServiceGeneralizationSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceGeneralizationSetAdapter() {
		if (serviceGeneralizationSetItemProvider == null) {
			serviceGeneralizationSetItemProvider = new ServiceGeneralizationSetItemProvider(this);
		}

		return serviceGeneralizationSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.SemanticPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticPackageItemProvider semanticPackageItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.SemanticPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticPackageAdapter() {
		if (semanticPackageItemProvider == null) {
			semanticPackageItemProvider = new SemanticPackageItemProvider(this);
		}

		return semanticPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.IRI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IRIItemProvider iriItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.IRI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIRIAdapter() {
		if (iriItemProvider == null) {
			iriItemProvider = new IRIItemProvider(this);
		}

		return iriItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyModelItemProvider vocabularyModelItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyModelAdapter() {
		if (vocabularyModelItemProvider == null) {
			vocabularyModelItemProvider = new VocabularyModelItemProvider(this);
		}

		return vocabularyModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Vocabulary} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyItemProvider vocabularyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Vocabulary}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyAdapter() {
		if (vocabularyItemProvider == null) {
			vocabularyItemProvider = new VocabularyItemProvider(this);
		}

		return vocabularyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Axiom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AxiomItemProvider axiomItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Axiom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAxiomAdapter() {
		if (axiomItemProvider == null) {
			axiomItemProvider = new AxiomItemProvider(this);
		}

		return axiomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Annotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationItemProvider annotationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Annotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAdapter() {
		if (annotationItemProvider == null) {
			annotationItemProvider = new AnnotationItemProvider(this);
		}

		return annotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyConstraints} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyConstraintsItemProvider vocabularyConstraintsItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyConstraints}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyConstraintsAdapter() {
		if (vocabularyConstraintsItemProvider == null) {
			vocabularyConstraintsItemProvider = new VocabularyConstraintsItemProvider(this);
		}

		return vocabularyConstraintsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.Association} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationItemProvider associationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.Association}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationAdapter() {
		if (associationItemProvider == null) {
			associationItemProvider = new AssociationItemProvider(this);
		}

		return associationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyAssociationItemProvider vocabularyAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyAssociationAdapter() {
		if (vocabularyAssociationItemProvider == null) {
			vocabularyAssociationItemProvider = new VocabularyAssociationItemProvider(this);
		}

		return vocabularyAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyPropertyItemProvider vocabularyPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyPropertyAdapter() {
		if (vocabularyPropertyItemProvider == null) {
			vocabularyPropertyItemProvider = new VocabularyPropertyItemProvider(this);
		}

		return vocabularyPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.ObjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectPropertyItemProvider objectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.ObjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectPropertyAdapter() {
		if (objectPropertyItemProvider == null) {
			objectPropertyItemProvider = new ObjectPropertyItemProvider(this);
		}

		return objectPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.DataProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPropertyItemProvider dataPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.DataProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPropertyAdapter() {
		if (dataPropertyItemProvider == null) {
			dataPropertyItemProvider = new DataPropertyItemProvider(this);
		}

		return dataPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.AnnotationProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationPropertyItemProvider annotationPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.AnnotationProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationPropertyAdapter() {
		if (annotationPropertyItemProvider == null) {
			annotationPropertyItemProvider = new AnnotationPropertyItemProvider(this);
		}

		return annotationPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyDataTypeItemProvider vocabularyDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyDataTypeAdapter() {
		if (vocabularyDataTypeItemProvider == null) {
			vocabularyDataTypeItemProvider = new VocabularyDataTypeItemProvider(this);
		}

		return vocabularyDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.NamedIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedIndividualItemProvider namedIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.NamedIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedIndividualAdapter() {
		if (namedIndividualItemProvider == null) {
			namedIndividualItemProvider = new NamedIndividualItemProvider(this);
		}

		return namedIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyClassItemProvider vocabularyClassItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyClassAdapter() {
		if (vocabularyClassItemProvider == null) {
			vocabularyClassItemProvider = new VocabularyClassItemProvider(this);
		}

		return vocabularyClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.AnonymousIndividual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnonymousIndividualItemProvider anonymousIndividualItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.AnonymousIndividual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnonymousIndividualAdapter() {
		if (anonymousIndividualItemProvider == null) {
			anonymousIndividualItemProvider = new AnonymousIndividualItemProvider(this);
		}

		return anonymousIndividualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link frameweb.VocabularyLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VocabularyLiteralItemProvider vocabularyLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link frameweb.VocabularyLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVocabularyLiteralAdapter() {
		if (vocabularyLiteralItemProvider == null) {
			vocabularyLiteralItemProvider = new VocabularyLiteralItemProvider(this);
		}

		return vocabularyLiteralItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (framewebProjectItemProvider != null) framewebProjectItemProvider.dispose();
		if (frameworkProfileItemProvider != null) frameworkProfileItemProvider.dispose();
		if (entityModelItemProvider != null) entityModelItemProvider.dispose();
		if (navigationModelItemProvider != null) navigationModelItemProvider.dispose();
		if (applicationModelItemProvider != null) applicationModelItemProvider.dispose();
		if (persistenceModelItemProvider != null) persistenceModelItemProvider.dispose();
		if (entityAssociationItemProvider != null) entityAssociationItemProvider.dispose();
		if (versionAttributeItemProvider != null) versionAttributeItemProvider.dispose();
		if (idAttributeItemProvider != null) idAttributeItemProvider.dispose();
		if (lobAttributeItemProvider != null) lobAttributeItemProvider.dispose();
		if (embeddedAttributeItemProvider != null) embeddedAttributeItemProvider.dispose();
		if (decimalAttributeItemProvider != null) decimalAttributeItemProvider.dispose();
		if (dateTimeAttributeItemProvider != null) dateTimeAttributeItemProvider.dispose();
		if (pageItemProvider != null) pageItemProvider.dispose();
		if (templateItemProvider != null) templateItemProvider.dispose();
		if (daoInterfaceItemProvider != null) daoInterfaceItemProvider.dispose();
		if (daoClassItemProvider != null) daoClassItemProvider.dispose();
		if (daoRealizationItemProvider != null) daoRealizationItemProvider.dispose();
		if (frontControllerClassItemProvider != null) frontControllerClassItemProvider.dispose();
		if (ioParameterItemProvider != null) ioParameterItemProvider.dispose();
		if (resultDependencyItemProvider != null) resultDependencyItemProvider.dispose();
		if (navigationAssociationItemProvider != null) navigationAssociationItemProvider.dispose();
		if (frontControllerMethodItemProvider != null) frontControllerMethodItemProvider.dispose();
		if (serviceClassItemProvider != null) serviceClassItemProvider.dispose();
		if (serviceInterfaceItemProvider != null) serviceInterfaceItemProvider.dispose();
		if (serviceGeneralizationItemProvider != null) serviceGeneralizationItemProvider.dispose();
		if (serviceControllerAssociationItemProvider != null) serviceControllerAssociationItemProvider.dispose();
		if (entityClassItemProvider != null) entityClassItemProvider.dispose();
		if (resultItemProvider != null) resultItemProvider.dispose();
		if (frontControllerDependencyItemProvider != null) frontControllerDependencyItemProvider.dispose();
		if (pageDependencyItemProvider != null) pageDependencyItemProvider.dispose();
		if (chainingDependencyItemProvider != null) chainingDependencyItemProvider.dispose();
		if (daoServiceAssociationItemProvider != null) daoServiceAssociationItemProvider.dispose();
		if (entityMethodItemProvider != null) entityMethodItemProvider.dispose();
		if (daoAttributeItemProvider != null) daoAttributeItemProvider.dispose();
		if (serviceMethodItemProvider != null) serviceMethodItemProvider.dispose();
		if (serviceAttributeItemProvider != null) serviceAttributeItemProvider.dispose();
		if (daoMethodItemProvider != null) daoMethodItemProvider.dispose();
		if (entityPackageItemProvider != null) entityPackageItemProvider.dispose();
		if (viewPackageItemProvider != null) viewPackageItemProvider.dispose();
		if (controllerPackageItemProvider != null) controllerPackageItemProvider.dispose();
		if (persistencePackageItemProvider != null) persistencePackageItemProvider.dispose();
		if (applicationPackageItemProvider != null) applicationPackageItemProvider.dispose();
		if (uiComponentItemProvider != null) uiComponentItemProvider.dispose();
		if (resultTypeItemProvider != null) resultTypeItemProvider.dispose();
		if (entityGeneralizationItemProvider != null) entityGeneralizationItemProvider.dispose();
		if (uiComponentFieldItemProvider != null) uiComponentFieldItemProvider.dispose();
		if (tagLibItemProvider != null) tagLibItemProvider.dispose();
		if (tagItemProvider != null) tagItemProvider.dispose();
		if (navigationCompositionPartItemProvider != null) navigationCompositionPartItemProvider.dispose();
		if (navigationCompositionWholeItemProvider != null) navigationCompositionWholeItemProvider.dispose();
		if (resultSetItemProvider != null) resultSetItemProvider.dispose();
		if (pageConstraintItemProvider != null) pageConstraintItemProvider.dispose();
		if (resultConstraintItemProvider != null) resultConstraintItemProvider.dispose();
		if (methodCosntraintItemProvider != null) methodCosntraintItemProvider.dispose();
		if (chainingConstraintItemProvider != null) chainingConstraintItemProvider.dispose();
		if (navigationGeneralizationItemProvider != null) navigationGeneralizationItemProvider.dispose();
		if (entityConstraintsItemProvider != null) entityConstraintsItemProvider.dispose();
		if (entityPropertyItemProvider != null) entityPropertyItemProvider.dispose();
		if (daoGeneralizationItemProvider != null) daoGeneralizationItemProvider.dispose();
		if (mappingLibItemProvider != null) mappingLibItemProvider.dispose();
		if (classMappingItemProvider != null) classMappingItemProvider.dispose();
		if (attributeMappingItemProvider != null) attributeMappingItemProvider.dispose();
		if (entityGeneralizationSetItemProvider != null) entityGeneralizationSetItemProvider.dispose();
		if (tagExtensionItemProvider != null) tagExtensionItemProvider.dispose();
		if (frameworkApplicationItemProvider != null) frameworkApplicationItemProvider.dispose();
		if (controllerExtensionItemProvider != null) controllerExtensionItemProvider.dispose();
		if (controllerItemProvider != null) controllerItemProvider.dispose();
		if (controllerSetItemProvider != null) controllerSetItemProvider.dispose();
		if (resultExtensionItemProvider != null) resultExtensionItemProvider.dispose();
		if (classMappingExtensionItemProvider != null) classMappingExtensionItemProvider.dispose();
		if (attributeMappingExtensionItemProvider != null) attributeMappingExtensionItemProvider.dispose();
		if (controllerExtensionEndItemProvider != null) controllerExtensionEndItemProvider.dispose();
		if (tagExtensionEndItemProvider != null) tagExtensionEndItemProvider.dispose();
		if (resultExtensionEndItemProvider != null) resultExtensionEndItemProvider.dispose();
		if (classMappingExtensionEndItemProvider != null) classMappingExtensionEndItemProvider.dispose();
		if (attributeMappingExtensionEndItemProvider != null) attributeMappingExtensionEndItemProvider.dispose();
		if (controllerPropertyItemProvider != null) controllerPropertyItemProvider.dispose();
		if (tagPropertyItemProvider != null) tagPropertyItemProvider.dispose();
		if (resultPropertyItemProvider != null) resultPropertyItemProvider.dispose();
		if (classMappingProperyItemProvider != null) classMappingProperyItemProvider.dispose();
		if (attributeMappingPropertyItemProvider != null) attributeMappingPropertyItemProvider.dispose();
		if (seviceRealizationItemProvider != null) seviceRealizationItemProvider.dispose();
		if (navigationGeneralizationSetItemProvider != null) navigationGeneralizationSetItemProvider.dispose();
		if (daoGeneralizationSetItemProvider != null) daoGeneralizationSetItemProvider.dispose();
		if (serviceGeneralizationSetItemProvider != null) serviceGeneralizationSetItemProvider.dispose();
		if (semanticPackageItemProvider != null) semanticPackageItemProvider.dispose();
		if (iriItemProvider != null) iriItemProvider.dispose();
		if (vocabularyModelItemProvider != null) vocabularyModelItemProvider.dispose();
		if (vocabularyItemProvider != null) vocabularyItemProvider.dispose();
		if (axiomItemProvider != null) axiomItemProvider.dispose();
		if (annotationItemProvider != null) annotationItemProvider.dispose();
		if (vocabularyConstraintsItemProvider != null) vocabularyConstraintsItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (associationItemProvider != null) associationItemProvider.dispose();
		if (vocabularyAssociationItemProvider != null) vocabularyAssociationItemProvider.dispose();
		if (vocabularyPropertyItemProvider != null) vocabularyPropertyItemProvider.dispose();
		if (objectPropertyItemProvider != null) objectPropertyItemProvider.dispose();
		if (dataPropertyItemProvider != null) dataPropertyItemProvider.dispose();
		if (annotationPropertyItemProvider != null) annotationPropertyItemProvider.dispose();
		if (vocabularyDataTypeItemProvider != null) vocabularyDataTypeItemProvider.dispose();
		if (namedIndividualItemProvider != null) namedIndividualItemProvider.dispose();
		if (vocabularyClassItemProvider != null) vocabularyClassItemProvider.dispose();
		if (anonymousIndividualItemProvider != null) anonymousIndividualItemProvider.dispose();
		if (vocabularyLiteralItemProvider != null) vocabularyLiteralItemProvider.dispose();
	}

}
