/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Classifier;
import uml2.Constraint;
import uml2.InputPin;
import uml2.OutputPin;

/**
 * A sample validator interface for {@link uml2.Action}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActionValidator {
	boolean validate();

	boolean validateContext(Classifier value);
	boolean validateInput(EList<InputPin> value);
	boolean validateIsLocallyReentrant(Boolean value);
	boolean validateLocalPostcondition(EList<Constraint> value);
	boolean validateLocalPrecondition(EList<Constraint> value);
	boolean validateOutput(EList<OutputPin> value);
}
