/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.ActivityEdge;
import uml2.ActivityGroup;
import uml2.ActivityNode;
import uml2.ActivityPartition;
import uml2.StructuredActivityNode;
import uml2.Variable;

/**
 * A sample validator interface for {@link uml2.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateEdge(EList<ActivityEdge> value);
	boolean validateGroup(EList<ActivityGroup> value);
	boolean validateStructuredNode(EList<StructuredActivityNode> value);
	boolean validateVariable(EList<Variable> value);
	boolean validateIsReadOnly(Boolean value);
	boolean validateIsSingleExecution(Boolean value);
	boolean validatePartition(EList<ActivityPartition> value);
	boolean validateNode(EList<ActivityNode> value);
}
