/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Activity;
import uml2.ActivityEdge;
import uml2.ActivityGroup;
import uml2.ActivityNode;
import uml2.ActivityPartition;
import uml2.InterruptibleActivityRegion;
import uml2.StructuredActivityNode;
import uml2.ValueSpecification;

/**
 * A sample validator interface for {@link uml2.ActivityEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityEdgeValidator {
	boolean validate();

	boolean validateGuard(ValueSpecification value);
	boolean validateInGroup(EList<ActivityGroup> value);
	boolean validateInPartition(EList<ActivityPartition> value);
	boolean validateInStructuredNode(StructuredActivityNode value);
	boolean validateInterrupts(InterruptibleActivityRegion value);
	boolean validateRedefinedEdge(EList<ActivityEdge> value);
	boolean validateSource(ActivityNode value);
	boolean validateTarget(ActivityNode value);
	boolean validateWeight(ValueSpecification value);
	boolean validateActivity(Activity value);
}
