/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Classifier;
import uml2.CollaborationUse;
import uml2.Feature;
import uml2.Generalization;
import uml2.GeneralizationSet;
import uml2.NamedElement;
import uml2.Property;
import uml2.Substitution;
import uml2.UseCase;

/**
 * A sample validator interface for {@link uml2.Classifier}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassifierValidator {
	boolean validate();

	boolean validateAttribute(EList<Property> value);
	boolean validateFeature(EList<Feature> value);
	boolean validateCollaborationUse(EList<CollaborationUse> value);
	boolean validateGeneral(EList<Classifier> value);
	boolean validateGeneralization(EList<Generalization> value);
	boolean validatePowertypeExtent(EList<GeneralizationSet> value);
	boolean validateInheritedMember(EList<NamedElement> value);
	boolean validateIsAbstract(Boolean value);
	boolean validateIsFinalSpecialization(Boolean value);
	boolean validateOwnedUseCase(EList<UseCase> value);
	boolean validateUseCase(EList<UseCase> value);
	boolean validateRedefinedClassifier(EList<Classifier> value);
	boolean validateRepresentation(CollaborationUse value);
	boolean validateSubstitution(EList<Substitution> value);
}
