/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.Deployment;

/**
 * A sample validator interface for {@link uml2.DeploymentSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentSpecificationValidator {
	boolean validate();

	boolean validateDeploymentLocation(String value);
	boolean validateExecutionLocation(String value);
	boolean validateDeployment(Deployment value);
}
