/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Comment;
import uml2.Element;

/**
 * A sample validator interface for {@link uml2.Element}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementValidator {
	boolean validate();

	boolean validateOwnedComment(EList<Comment> value);
	boolean validateOwnedElement(EList<Element> value);
	boolean validateOwner(Element value);
}
