/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.UseCase;

/**
 * A sample validator interface for {@link uml2.Include}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IncludeValidator {
	boolean validate();

	boolean validateAddition(UseCase value);
	boolean validateIncludingCase(UseCase value);
}
