/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Classifier;
import uml2.Slot;
import uml2.ValueSpecification;

/**
 * A sample validator interface for {@link uml2.InstanceSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstanceSpecificationValidator {
	boolean validate();

	boolean validateClassifier(EList<Classifier> value);
	boolean validateSlot(EList<Slot> value);
	boolean validateSpecification(ValueSpecification value);
}
