/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.BehavioredClassifier;
import uml2.Interface;

/**
 * A sample validator interface for {@link uml2.InterfaceRealization}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceRealizationValidator {
	boolean validate();

	boolean validateContract(Interface value);
	boolean validateImplementingClassifier(BehavioredClassifier value);
}
