/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.InputPin;
import uml2.LinkEndData;

/**
 * A sample validator interface for {@link uml2.LinkAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LinkActionValidator {
	boolean validate();

	boolean validateEndData(EList<LinkEndData> value);
	boolean validateInputValue(EList<InputPin> value);
}
