/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Connector;
import uml2.Interaction;
import uml2.MessageEnd;
import uml2.MessageKind;
import uml2.MessageSort;
import uml2.NamedElement;
import uml2.ValueSpecification;

/**
 * A sample validator interface for {@link uml2.Message}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageValidator {
	boolean validate();

	boolean validateArgument(EList<ValueSpecification> value);
	boolean validateConnector(Connector value);
	boolean validateInteraction(Interaction value);
	boolean validateMessageKind(MessageKind value);
	boolean validateMessageSort(MessageSort value);
	boolean validateReceiveEvent(MessageEnd value);
	boolean validateSendEvent(MessageEnd value);
	boolean validateSignature(NamedElement value);
}
