/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Dependency;
import uml2.Namespace;
import uml2.StringExpression;
import uml2.VisibilityKind;

/**
 * A sample validator interface for {@link uml2.NamedElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamedElementValidator {
	boolean validate();

	boolean validateClientDependency(EList<Dependency> value);
	boolean validateName(String value);
	boolean validateNameExpression(StringExpression value);
	boolean validateNamespace(Namespace value);
	boolean validateQualifiedName(String value);
	boolean validateVisibility(VisibilityKind value);
}
