/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Constraint;
import uml2.ElementImport;
import uml2.NamedElement;
import uml2.PackageImport;
import uml2.PackageableElement;

/**
 * A sample validator interface for {@link uml2.Namespace}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NamespaceValidator {
	boolean validate();

	boolean validateElementImport(EList<ElementImport> value);
	boolean validateImportedMember(EList<PackageableElement> value);
	boolean validateMember(EList<NamedElement> value);
	boolean validateOwnedMember(EList<NamedElement> value);
	boolean validateOwnedRule(EList<Constraint> value);
	boolean validatePackageImport(EList<PackageImport> value);
}
