/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.Profile;

/**
 * A sample validator interface for {@link uml2.ProfileApplication}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProfileApplicationValidator {
	boolean validate();

	boolean validateAppliedProfile(Profile value);
	boolean validateIsStrict(Boolean value);
	boolean validateApplyingPackage(uml2.Package value);
}
