/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.Behavior;
import uml2.InputPin;
import uml2.OutputPin;

/**
 * A sample validator interface for {@link uml2.ReduceAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReduceActionValidator {
	boolean validate();

	boolean validateCollection(InputPin value);
	boolean validateIsOrdered(Boolean value);
	boolean validateReducer(Behavior value);
	boolean validateResult(OutputPin value);
}
