/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Region;
import uml2.State;
import uml2.StateMachine;
import uml2.Transition;
import uml2.Vertex;

/**
 * A sample validator interface for {@link uml2.Region}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RegionValidator {
	boolean validate();

	boolean validateExtendedRegion(Region value);
	boolean validateState(State value);
	boolean validateStateMachine(StateMachine value);
	boolean validateTransition(EList<Transition> value);
	boolean validateSubvertex(EList<Vertex> value);
}
