/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Pseudostate;
import uml2.Region;
import uml2.State;
import uml2.StateMachine;

/**
 * A sample validator interface for {@link uml2.StateMachine}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StateMachineValidator {
	boolean validate();

	boolean validateConnectionPoint(EList<Pseudostate> value);
	boolean validateSubmachineState(EList<State> value);
	boolean validateRegion(EList<Region> value);
	boolean validateExtendedStateMachine(EList<StateMachine> value);
}
