/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.ParameterableElement;
import uml2.TemplateBinding;
import uml2.TemplateParameter;

/**
 * A sample validator interface for {@link uml2.TemplateParameterSubstitution}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemplateParameterSubstitutionValidator {
	boolean validate();

	boolean validateActual(ParameterableElement value);
	boolean validateFormal(TemplateParameter value);
	boolean validateOwnedActual(ParameterableElement value);
	boolean validateTemplateBinding(TemplateBinding value);
}
