/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.TemplateBinding;
import uml2.TemplateSignature;

/**
 * A sample validator interface for {@link uml2.TemplateableElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemplateableElementValidator {
	boolean validate();

	boolean validateTemplateBinding(EList<TemplateBinding> value);
	boolean validateOwnedTemplateSignature(TemplateSignature value);
}
