/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.NamedElement;

/**
 * A sample validator interface for {@link uml2.TimeObservation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimeObservationValidator {
	boolean validate();

	boolean validateEvent(NamedElement value);
	boolean validateFirstEvent(Boolean value);
}
