/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.Activity;
import uml2.StructuredActivityNode;

/**
 * A sample validator interface for {@link uml2.Variable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableValidator {
	boolean validate();

	boolean validateActivityScope(Activity value);
	boolean validateScope(StructuredActivityNode value);
}
