/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.DAOAttribute;
import frameweb.DAOBaseOperation;
import frameweb.DAOClassName;
import frameweb.DAOOperation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.DAOClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DAOClassValidator {
	boolean validate();

	boolean validateBaseImplements(EList<DAOBaseOperation> value);
	boolean validateDAOImplements(EList<DAOOperation> value);
	boolean validateDAOClassName(DAOClassName value);
	boolean validateDAOClassAttribute(EList<DAOAttribute> value);
}
