/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.FrameWebModel;
import frameweb.Framework;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link frameweb.Frameweb}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FramewebValidator {
	boolean validate();

	boolean validateCompose(EList<FrameWebModel> value);
	boolean validateUses(EList<Framework> value);
}
