/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Component;
import frameweb.Form;
import frameweb.FrontControllerClass;
import frameweb.FrontControllerMethod;
import frameweb.JQuery;
import frameweb.Page;
import frameweb.Template;

/**
 * A sample validator interface for {@link frameweb.FrontControllerDependence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FrontControllerDependenceValidator {
	boolean validate();

	boolean validateMethod(FrontControllerMethod value);
	boolean validateSourceForm(Form value);
	boolean validateTargetFrontController(FrontControllerClass value);
	boolean validateSourcePage(Page value);
	boolean validateSourceTemplate(Template value);
	boolean validateSourceComponent(Component value);
	boolean validateSourceJQuery(JQuery value);
}
