/**
 *
 * $Id$
 */
package frameweb.validation;

import frameweb.Page;
import frameweb.Template;

/**
 * A sample validator interface for {@link frameweb.PageDependency}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PageDependencyValidator {
	boolean validate();

	boolean validateTargetPage(Page value);
	boolean validateSourceTemplate(Template value);
	boolean validateLinkHTML(String value);
	boolean validateSourcePage(Page value);
}
