/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.OutputPin;
import uml2.Trigger;

/**
 * A sample validator interface for {@link uml2.AcceptEventAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AcceptEventActionValidator {
	boolean validate();

	boolean validateIsUnmarshall(Boolean value);
	boolean validateResult(EList<OutputPin> value);
	boolean validateTrigger(EList<Trigger> value);
}
