/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.ActivityEdge;
import uml2.ActivityNode;
import uml2.ActivityPartition;
import uml2.Element;

/**
 * A sample validator interface for {@link uml2.ActivityPartition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityPartitionValidator {
	boolean validate();

	boolean validateIsDimension(Boolean value);
	boolean validateIsExternal(Boolean value);
	boolean validateNode(EList<ActivityNode> value);
	boolean validateRepresents(Element value);
	boolean validateSubpartition(EList<ActivityPartition> value);
	boolean validateSuperPartition(ActivityPartition value);
	boolean validateEdge(EList<ActivityEdge> value);
}
