/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Property;
import uml2.Type;

/**
 * A sample validator interface for {@link uml2.Association}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationValidator {
	boolean validate();

	boolean validateEndType(EList<Type> value);
	boolean validateIsDerived(Boolean value);
	boolean validateNavigableOwnedEnd(EList<Property> value);
	boolean validateOwnedEnd(EList<Property> value);
	boolean validateMemberEnd(EList<Property> value);
}
