/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Behavior;
import uml2.CallConcurrencyKind;
import uml2.Parameter;
import uml2.ParameterSet;
import uml2.Type;

/**
 * A sample validator interface for {@link uml2.BehavioralFeature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BehavioralFeatureValidator {
	boolean validate();

	boolean validateConcurrency(CallConcurrencyKind value);
	boolean validateIsAbstract(Boolean value);
	boolean validateMethod(EList<Behavior> value);
	boolean validateOwnedParameter(EList<Parameter> value);
	boolean validateOwnedParameterSet(EList<ParameterSet> value);
	boolean validateRaisedException(EList<Type> value);
}
