/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Behavior;
import uml2.BehavioralFeature;
import uml2.BehavioredClassifier;
import uml2.Constraint;
import uml2.Parameter;
import uml2.ParameterSet;

/**
 * A sample validator interface for {@link uml2.Behavior}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BehaviorValidator {
	boolean validate();

	boolean validateContext(BehavioredClassifier value);
	boolean validateIsReentrant(Boolean value);
	boolean validateOwnedParameter(EList<Parameter> value);
	boolean validateOwnedParameterSet(EList<ParameterSet> value);
	boolean validatePostcondition(EList<Constraint> value);
	boolean validatePrecondition(EList<Constraint> value);
	boolean validateRedefinedBehavior(EList<Behavior> value);
	boolean validateSpecification(BehavioralFeature value);
}
