/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Classifier;
import uml2.Extension;
import uml2.Operation;
import uml2.Reception;

/**
 * A sample validator interface for {@link uml2.Class}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassValidator {
	boolean validate();

	boolean validateOwnedOperation(EList<Operation> value);
	boolean validateExtension(EList<Extension> value);
	boolean validateIsActive(Boolean value);
	boolean validateNestedClassifier(EList<Classifier> value);
	boolean validateOwnedReception(EList<Reception> value);
	boolean validateSuperClass(EList<uml2.Class> value);
}
