/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Clause;
import uml2.ExecutableNode;
import uml2.OutputPin;

/**
 * A sample validator interface for {@link uml2.Clause}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClauseValidator {
	boolean validate();

	boolean validateBody(EList<ExecutableNode> value);
	boolean validateBodyOutput(EList<OutputPin> value);
	boolean validateDecider(OutputPin value);
	boolean validatePredecessorClause(EList<Clause> value);
	boolean validateSuccessorClause(EList<Clause> value);
	boolean validateTest(EList<ExecutableNode> value);
}
