/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.ComponentRealization;
import uml2.Interface;
import uml2.PackageableElement;

/**
 * A sample validator interface for {@link uml2.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateIsIndirectlyInstantiated(Boolean value);
	boolean validatePackagedElement(EList<PackageableElement> value);
	boolean validateProvided(EList<Interface> value);
	boolean validateRealization(EList<ComponentRealization> value);
	boolean validateRequired(EList<Interface> value);
}
