/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Association;
import uml2.Behavior;
import uml2.Connector;
import uml2.ConnectorEnd;
import uml2.ConnectorKind;

/**
 * A sample validator interface for {@link uml2.Connector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectorValidator {
	boolean validate();

	boolean validateContract(EList<Behavior> value);
	boolean validateEnd(EList<ConnectorEnd> value);
	boolean validateKind(ConnectorKind value);
	boolean validateRedefinedConnector(EList<Connector> value);
	boolean validateType(Association value);
}
