/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Pseudostate;
import uml2.State;

/**
 * A sample validator interface for {@link uml2.ConnectionPointReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionPointReferenceValidator {
	boolean validate();

	boolean validateEntry(EList<Pseudostate> value);
	boolean validateExit(EList<Pseudostate> value);
	boolean validateState(State value);
}
