/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.Behavior;
import uml2.ObjectFlow;

/**
 * A sample validator interface for {@link uml2.DecisionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DecisionNodeValidator {
	boolean validate();

	boolean validateDecisionInput(Behavior value);
	boolean validateDecisionInputFlow(ObjectFlow value);
}
