/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.Namespace;
import uml2.PackageableElement;
import uml2.VisibilityKind;

/**
 * A sample validator interface for {@link uml2.ElementImport}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementImportValidator {
	boolean validate();

	boolean validateAlias(String value);
	boolean validateImportedElement(PackageableElement value);
	boolean validateVisibility(VisibilityKind value);
	boolean validateImportingNamespace(Namespace value);
}
