/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.ExpansionRegion;

/**
 * A sample validator interface for {@link uml2.ExpansionNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpansionNodeValidator {
	boolean validate();

	boolean validateRegionAsInput(ExpansionRegion value);
	boolean validateRegionAsOutput(ExpansionRegion value);
}
