/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Gate;
import uml2.Interaction;
import uml2.Property;
import uml2.ValueSpecification;

/**
 * A sample validator interface for {@link uml2.InteractionUse}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InteractionUseValidator {
	boolean validate();

	boolean validateActualGate(EList<Gate> value);
	boolean validateArgument(EList<ValueSpecification> value);
	boolean validateRefersTo(Interaction value);
	boolean validateReturnValue(ValueSpecification value);
	boolean validateReturnValueRecipient(Property value);
}
