/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.InteractionConstraint;
import uml2.InteractionFragment;

/**
 * A sample validator interface for {@link uml2.InteractionOperand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InteractionOperandValidator {
	boolean validate();

	boolean validateGuard(InteractionConstraint value);
	boolean validateFragment(EList<InteractionFragment> value);
}
