/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.ActivityEdge;
import uml2.ActivityNode;

/**
 * A sample validator interface for {@link uml2.InterruptibleActivityRegion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterruptibleActivityRegionValidator {
	boolean validate();

	boolean validateNode(EList<ActivityNode> value);
	boolean validateInterruptingEdge(EList<ActivityEdge> value);
}
