/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.ExecutableNode;
import uml2.InputPin;
import uml2.OutputPin;

/**
 * A sample validator interface for {@link uml2.LoopNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopNodeValidator {
	boolean validate();

	boolean validateBodyOutput(EList<OutputPin> value);
	boolean validateBodyPart(EList<ExecutableNode> value);
	boolean validateDecider(OutputPin value);
	boolean validateIsTestedFirst(Boolean value);
	boolean validateLoopVariable(EList<OutputPin> value);
	boolean validateLoopVariableInput(EList<InputPin> value);
	boolean validateResult(EList<OutputPin> value);
	boolean validateSetupPart(EList<ExecutableNode> value);
	boolean validateTest(EList<ExecutableNode> value);
}
