/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Behavior;
import uml2.Parameter;

/**
 * A sample validator interface for {@link uml2.OpaqueExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OpaqueExpressionValidator {
	boolean validate();

	boolean validateBehavior(Behavior value);
	boolean validateBody(EList<String> value);
	boolean validateLanguage(EList<String> value);
	boolean validateResult(Parameter value);
}
