/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.PackageMerge;
import uml2.PackageableElement;
import uml2.ProfileApplication;
import uml2.Stereotype;
import uml2.Type;

/**
 * A sample validator interface for {@link uml2.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
	boolean validate();

	boolean validateUri(String value);
	boolean validateNestedPackage(EList<uml2.Package> value);
	boolean validateNestingPackage(uml2.Package value);
	boolean validateOwnedStereotype(EList<Stereotype> value);
	boolean validatePackageMerge(EList<PackageMerge> value);
	boolean validatePackagedElement(EList<PackageableElement> value);
	boolean validateProfileApplication(EList<ProfileApplication> value);
	boolean validateOwnedType(EList<Type> value);
}
