/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Operation;
import uml2.ParameterDirectionKind;
import uml2.ParameterEffectKind;
import uml2.ParameterSet;
import uml2.ValueSpecification;

/**
 * A sample validator interface for {@link uml2.Parameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterValidator {
	boolean validate();

	boolean validateDefault(String value);
	boolean validateDefaultValue(ValueSpecification value);
	boolean validateDirection(ParameterDirectionKind value);
	boolean validateEffect(ParameterEffectKind value);
	boolean validateIsException(Boolean value);
	boolean validateIsStream(Boolean value);
	boolean validateOperation(Operation value);
	boolean validateParameterSet(EList<ParameterSet> value);
}
