/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Interface;
import uml2.Port;
import uml2.ProtocolStateMachine;

/**
 * A sample validator interface for {@link uml2.Port}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PortValidator {
	boolean validate();

	boolean validateIsBehavior(Boolean value);
	boolean validateIsConjugated(Boolean value);
	boolean validateIsService(Boolean value);
	boolean validateProtocol(ProtocolStateMachine value);
	boolean validateProvided(EList<Interface> value);
	boolean validateRedefinedPort(EList<Port> value);
	boolean validateRequired(EList<Interface> value);
}
