/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.ActivityEdge;
import uml2.ActivityNode;
import uml2.InputPin;
import uml2.OutputPin;
import uml2.Variable;

/**
 * A sample validator interface for {@link uml2.StructuredActivityNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StructuredActivityNodeValidator {
	boolean validate();

	boolean validateMustIsolate(Boolean value);
	boolean validateNode(EList<ActivityNode> value);
	boolean validateStructuredNodeInput(EList<InputPin> value);
	boolean validateStructuredNodeOutput(EList<OutputPin> value);
	boolean validateVariable(EList<Variable> value);
	boolean validateEdge(EList<ActivityEdge> value);
}
