/**
 *
 * $Id$
 */
package uml2.validation;

import uml2.ParameterableElement;
import uml2.TemplateSignature;

/**
 * A sample validator interface for {@link uml2.TemplateParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemplateParameterValidator {
	boolean validate();

	boolean validateDefault(ParameterableElement value);
	boolean validateOwnedDefault(ParameterableElement value);
	boolean validateParameteredElement(ParameterableElement value);
	boolean validateSignature(TemplateSignature value);
	boolean validateOwnedParameteredElement(ParameterableElement value);
}
