/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Observation;
import uml2.ValueSpecification;

/**
 * A sample validator interface for {@link uml2.TimeExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimeExpressionValidator {
	boolean validate();

	boolean validateExpr(ValueSpecification value);
	boolean validateObservation(EList<Observation> value);
}
