/**
 *
 * $Id$
 */
package uml2.validation;

import org.eclipse.emf.common.util.EList;

import uml2.Classifier;
import uml2.Extend;
import uml2.ExtensionPoint;
import uml2.Include;

/**
 * A sample validator interface for {@link uml2.UseCase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UseCaseValidator {
	boolean validate();

	boolean validateExtend(EList<Extend> value);
	boolean validateExtensionPoint(EList<ExtensionPoint> value);
	boolean validateInclude(EList<Include> value);
	boolean validateSubject(EList<Classifier> value);
}
