<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="frameweb" nsURI="http://nemo.inf.ufes.br/projects/frameweb/2015"
    nsPrefix="frameweb">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Frameweb">
    <eAnnotations source="Ecore">
      <details key="constraints" value="FramewebMinimum"/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//Frameweb/%Ecore%/@details.0">
      <details key="FramewebMinimum" value="(self.Compose->size()>=1 and self.Configures->size()=0) or &#xD;&#xA;(self.Configures->size()>=1 and self.Compose->size()=0)"/>
    </eAnnotations>
    <eAnnotations source="Comments" references="#//Frameweb/%Ecore%/@details.0">
      <details key="FramewebMininimum" value="The Frameweb need obligatorily have a Framework Profile or FramewebModel and can not have both simultaneously"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Compose" upperBound="-1"
        eType="#//FrameWebModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Configures" upperBound="-1"
        eType="#//FrameworkProfile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameWebModel" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Model">
    <eAnnotations source="Ecore">
      <details key="constraints" value="FramewebModelContent"/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//FrameWebModel/%Ecore%/@details.0">
      <details key="FramewebModelContent" value=""/>
    </eAnnotations>
    <eAnnotations source="Comments" references="#//FrameWebModel/%Ecore%/@details.0">
      <details key="FramewebModelContent" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameworkProfile" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Profile">
    <eAnnotations source="Ecore">
      <details key="constraints" value="FrameworkResultSetConstraint FrameworkTagLibConstraint"/>
    </eAnnotations>
    <eAnnotations source="Comments"/>
    <eAnnotations source="OCL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//FrameworkCategoryList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//FrameworkKindList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainModel" eSuperTypes="#//FrameWebModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="DomainModelContent DomainModelMinimum"/>
    </eAnnotations>
    <eAnnotations source="comments" references="#//DomainModel/%http:%2F%2Fwww.eclipse.org%2Femf%2F2002%2FEcore%/@details.0">
      <details key="DomainModelContent" value="A DomainModel must have only DomainPackage."/>
      <details key="DomainModelMinimum" value="A DomainModel must have at least one DomainPackage"/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//DomainModel/%http:%2F%2Fwww.eclipse.org%2Femf%2F2002%2FEcore%/@details.0">
      <details key="DomainModelContent" value="self.packagedElement.oclIsType(DomainPackage"/>
      <details key="DomaniModelMinimum" value="self.packagedElement->size()>=1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationModel" eSuperTypes="#//FrameWebModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationModel" eSuperTypes="#//FrameWebModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersistenceModel" eSuperTypes="#//FrameWebModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAssociation" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="#//Collection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cascade" eType="#//Cascade"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetch" eType="#//Fetch"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="#//Order"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainAttribute" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPersistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionAttribute" eSuperTypes="#//DomainAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdAttribute" eSuperTypes="#//DomainAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generation" eType="#//Generation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LOBAttribute" eSuperTypes="#//DomainAttribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedAttribute" eSuperTypes="#//DomainAttribute"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DateTimePrecision">
    <eLiterals name="timestamp"/>
    <eLiterals name="time" value="1"/>
    <eLiterals name="date" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Generation">
    <eLiterals name="auto"/>
    <eLiterals name="identity" value="1"/>
    <eLiterals name="sequence" value="2"/>
    <eLiterals name="none" value="3"/>
    <eLiterals name="table" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalAttribute" eSuperTypes="#//DomainAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimalPrecision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimalScale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeAttribute" eSuperTypes="#//DomainAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateTimePrecision" eType="#//DateTimePrecision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Collection">
    <eLiterals name="set"/>
    <eLiterals name="bag" value="1"/>
    <eLiterals name="list" value="2"/>
    <eLiterals name="map" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Order">
    <eLiterals name="natural"/>
    <eLiterals name="columnNameAsc" value="1"/>
    <eLiterals name="columnNameDesc" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cascade">
    <eLiterals name="remove"/>
    <eLiterals name="merge" value="1"/>
    <eLiterals name="refresh" value="2"/>
    <eLiterals name="persist" value="3"/>
    <eLiterals name="none" value="4"/>
    <eLiterals name="all" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fetch">
    <eLiterals name="eager"/>
    <eLiterals name="lazy" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//NavigationClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PageTagLib" upperBound="-1"
        eType="#//TagLib"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template" eSuperTypes="#//NavigationClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TemplateTagLib" upperBound="-1"
        eType="#//TagLib"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOInterface" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infix" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sufix" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        changeable="false" defaultValueLiteral="DAO"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sufix" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        changeable="false" defaultValueLiteral="" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infix" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        changeable="false" defaultValueLiteral="DAO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"
        changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAORealization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InterfaceRealization"/>
  <eClassifiers xsi:type="ecore:EClass" name="FrontControllerClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="IOParameter" eSuperTypes="#//NavigationAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="display" upperBound="-1"
        eType="#//UIComponentField" derived="true" eOpposite="#//UIComponentField/inject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FrameworkCategoryList">
    <eLiterals name="FrontController" literal="FrontController"/>
    <eLiterals name="DependencyInjection" value="1" literal="DependencyInjection"/>
    <eLiterals name="ObjetoRelacional" value="2" literal="ObjetoRelacional"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultDependency" eSuperTypes="#//NavigationDependency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ResultDependencyConstraint&#xD;&#xA;"/>
    </eAnnotations>
    <eAnnotations source="Comments" references="#//ResultDependency/%http:%2F%2Fwww.eclipse.org%2Femf%2F2002%2FEcore%/@details.0">
      <details key="ResultDependencyConstraint" value="A ResultDependency must have a FrontControllerClass as client and a NavigationClass as supplier."/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//ResultDependency/%http:%2F%2Fwww.eclipse.org%2Femf%2F2002%2FEcore%/@details.0">
      <details key="ResultDependencyConstraint" value="(self.oclAsType(Dependency).client.oclIsTypeOf(FrontControllerClass)) and&#xD;&#xA;(self.oclAsType(Dependency).supplier.oclIsTypeOf(NavigationClass))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResultResult" upperBound="-1"
        eType="#//Result"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResultMethod" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResultDependendencyCosntraint"
        ordered="false" lowerBound="1" eType="#//ResultConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="render" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="@none"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="execute" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="@this"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ajax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationAssociation" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="FrontControllerMethod" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterface" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceControllerAssociation" eSuperTypes="#//ServiceAssociation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainClass" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstantNameList">
    <eLiterals name="DAO"/>
    <eLiterals name="interface" value="1"/>
    <eLiterals name="base" value="2"/>
    <eLiterals name="class" value="3"/>
    <eLiterals name="impl" value="4"/>
    <eLiterals name="Controller" literal="Controller"/>
    <eLiterals name="Domain"/>
    <eLiterals name="Persistence" literal="Persistence"/>
    <eLiterals name="Application"/>
    <eLiterals name="View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="FrontControllerDependency" eSuperTypes="#//NavigationDependency">
    <eAnnotations source="Ecore">
      <details key="constraints" value="FrontControllerDependencyConstraint"/>
    </eAnnotations>
    <eAnnotations source="Comments" references="#//FrontControllerDependency/%Ecore%/@details.0">
      <details key="FrontControllerDependencyConstraint" value="A FrontControllerDependencyConstraint must have a NavigationClass as client and a FrontControllerClass as supplier."/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//FrontControllerDependency/%Ecore%/@details.0">
      <details key="FrontControllerDependencyConstraint" value="context FrontControllerDependency &#xD;&#xA; inv: &#xD;&#xA;  (self.oclAsType(Dependency).supplier.oclIsTypeOf(FrontControllerClass)) and&#xD;&#xA;  (self.oclAsType(Dependency).client.oclIsTypeOf(NavigationClass)) "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Method" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MethodDependendencyConstraint"
        ordered="false" lowerBound="1" eType="#//MethodCosntraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageDependency" eSuperTypes="#//NavigationDependency">
    <eAnnotations source="Ecore">
      <details key="constraints" value="PageDepencencyConstraint"/>
    </eAnnotations>
    <eAnnotations source="Comments" references="#//PageDependency/%Ecore%/@details.0">
      <details key="PageDepencencyConstraint" value="A PageDependencyConstraint must have a Page as client and a Page or a Template as supplier."/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//PageDependency/%Ecore%/@details.0">
      <details key="PageDepencencyConstraint" value="context PageDependency &#xD;&#xA; inv: &#xD;&#xA;  (self.oclAsType(Dependency).client.oclIsTypeOf(Page)) and&#xD;&#xA;  ((self.oclAsType(Dependency).supplier.oclIsTypeOf(Page)) or&#xD;&#xA;  (self.oclAsType(Dependency).supplier.oclIsTypeOf(Template)))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PageDependencyCosntraint"
        ordered="false" lowerBound="1" eType="#//PageConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChainingDependency" eSuperTypes="#//NavigationDependency">
    <eAnnotations source="Ecore">
      <details key="constraints" value="ChainingDependencyConstraint"/>
    </eAnnotations>
    <eAnnotations source="Comments" references="#//ChainingDependency/%Ecore%/@details.0">
      <details key="ChainingDependencyConstraint" value="A ChainingDependencyConstraint must have a FrontControllerClass as client and a FrontControllerClass as supplier and these client and supplier can not be the same."/>
    </eAnnotations>
    <eAnnotations source="OCL" references="#//ChainingDependency/%Ecore%/@details.0">
      <details key="ChainingDependencyConstraint" value="context ChainingDependency &#xD;&#xA; inv: &#xD;&#xA;  (self.oclAsType(Dependency).supplier.oclIsTypeOf(FrontControllerClass)) and&#xD;&#xA;  (self.oclAsType(Dependency).client.oclIsTypeOf(FrontControllerClass)) and &#xD;&#xA;  (self.oclAsType(Dependency).supplier &lt;> self.oclAsType(Dependency).client) "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OutMethod" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InMethod" lowerBound="1"
        eType="#//FrontControllerMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChainingDependendencyConstraint"
        ordered="false" lowerBound="1" eType="#//ChainingConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAOServiceAssociation" eSuperTypes="#//ServiceAssociation"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationAttribute" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EEnum" name="InheritanceMapping">
    <eLiterals name="singletable"/>
    <eLiterals name="union" value="1"/>
    <eLiterals name="join" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationClass" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainMethod" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAOAttribute" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceMethod" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAttribute" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceAssociation" abstract="true"
      interface="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationDependency" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAOMethod" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainPackage" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewPackage" eSuperTypes="#//NavigationPackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerPackage" eSuperTypes="#//NavigationPackage"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersistencePackage" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationPackage" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIComponent" eSuperTypes="#//NavigationClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultType" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationPackage" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIComponentField" instanceClassName="UIComponent"
      eSuperTypes="#//NavigationAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inject" eType="#//IOParameter"
        eOpposite="#//IOParameter/display"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagLib" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationCompositionPart" eSuperTypes="#//NavigationProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationCompositionWhole" eSuperTypes="#//NavigationProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationProperty" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultSet" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationConstraint" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageConstraint" eSuperTypes="#//NavigationConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultConstraint" eSuperTypes="#//NavigationConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCosntraint" eSuperTypes="#//NavigationConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChainingConstraint" eSuperTypes="#//NavigationConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainConstraints" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainProperty" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAOGeneralization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Generalization"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingLib" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMapping" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeMapping" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainGeneralizationSet" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//GeneralizationSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping" eType="#//InheritanceMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameworkExtension" abstract="true"
      eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Extension"/>
  <eClassifiers xsi:type="ecore:EClass" name="TagExtension" eSuperTypes="#//NavigationExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="Framework" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ProfileApplication"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FrameworkKindList">
    <eLiterals name="StandardSpecification" literal="StandardSpecification"/>
    <eLiterals name="FrameworkSpecification" value="1"/>
    <eLiterals name="FrameworkImplementation" value="2"/>
    <eLiterals name="Custom" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerExtension" eSuperTypes="#//NavigationExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Stereotype"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerSet" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultExtension" eSuperTypes="#//NavigationExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMappingExtension" eSuperTypes="#//DomainExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeMappingExtension" eSuperTypes="#//DomainExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerExtensionEnd" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExtensionEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="TagExtensionEnd" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExtensionEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultExtensionEnd" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExtensionEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMappingExtensionEnd" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExtensionEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeMappingExtensionEnd" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ExtensionEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerProperty" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="TagProperty" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResultProperty" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassMappingPropery" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeMappingProperty" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="SeviceRealization" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InterfaceRealization"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationExtension" abstract="true"
      eSuperTypes="#//FrameworkExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainExtension" abstract="true" eSuperTypes="#//FrameworkExtension"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationGeneralizationSet" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//GeneralizationSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAOGeneralizationSet" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//GeneralizationSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceGeneralizationSet" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//GeneralizationSet"/>
</ecore:EPackage>
